Start work on Oritech JEI Plugin
FTBTeam/FTB-JEI-Extras pull request #3
Opened 2024-12-02 21:18 UTC by UnRealDinnerbone

2024-12-02 21:25 UTC, UnRealDinnerbone commented on build.gradle
Yes I know this is not matching what in the build.gradle atm. I was fighting with gradle and this is what I got working

2024-12-04 16:37 UTC, MichaelHillcox requested changes

2024-12-04 16:37 UTC, MichaelHillcox commented on CHANGELOG.md
> +- Advanced AE JEI Compact
More info please

2024-12-04 16:37 UTC, MichaelHillcox commented on build.gradle
> +    implementation("curse.maven:oritech-1030830:5952879")
Plz follow the gradle, shouldn't take more than a few minutes

2024-12-04 16:55 UTC, MichaelHillcox approved these changes

2024-12-04 16:56 UTC, merged